### ISSUE TITLE
Unable to RENDER

### ISSUE THREAD

**Issue by AnandPilania** [ikkez/f3-template-sections#1]
Hi @ikkez , I'm trying this plugin for `meta` use, like:

`layout file`:
```
<head>
    <F3::section id="meta">&nbsp;</F3::section>
</head>
```

`route file`:
```
<body>
    <F3::inject id="meta">
        .... CONTENT ...
    </F3::inject>
</body>
```

Now, i'm getting
```
<head>
    <F3::section id="meta">&nbsp;</F3::section>
</head>
<body>
    <F3::inject id="meta">
        .... CONTENT ...
    </F3::inject>
</body>
```
instead of:
```
<head>
    ... CONTENT ...
</head>
```

Is i'm misinterpreting this plugin for that scenario or missed something to implement?

Regards

**Comment by ikkez** [comment]
Looks like you have not initialized the plugin yet. please see https://github.com/ikkez/f3-template-sections#initialize
you need to use the Template engine of course to make this work.
